// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5AyEmIuzgroMYzKEGu6iMzLJMPKzDwgc',
    appId: '1:706267674322:web:be58f968e7a23bada1df0b',
    messagingSenderId: '706267674322',
    projectId: 'speed-chat25',
    authDomain: 'speed-chat25.firebaseapp.com',
    storageBucket: 'speed-chat25.firebasestorage.app',
    measurementId: 'G-223V7PHQDS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvtSRwX0R6Tex5kXt-Gj3z_AmvPOctay4',
    appId: '1:706267674322:android:227702cb3f8325e4a1df0b',
    messagingSenderId: '706267674322',
    projectId: 'speed-chat25',
    storageBucket: 'speed-chat25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDYvFGL9kqI3uDXN-l-eya8DY2-JiNERE',
    appId: '1:706267674322:ios:992468320c44a3eda1df0b',
    messagingSenderId: '706267674322',
    projectId: 'speed-chat25',
    storageBucket: 'speed-chat25.firebasestorage.app',
    iosBundleId: 'com.example.speedChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDYvFGL9kqI3uDXN-l-eya8DY2-JiNERE',
    appId: '1:706267674322:ios:992468320c44a3eda1df0b',
    messagingSenderId: '706267674322',
    projectId: 'speed-chat25',
    storageBucket: 'speed-chat25.firebasestorage.app',
    iosBundleId: 'com.example.speedChat',
  );
}
